# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 黑猫的博客
email: bertonzh@gmail.com
description: > 记录代码和生活
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cateyes.blue" # the base hostname & protocol for your site
twitter_username: meowtec
github_username:  meowtec

# Build settings
markdown: kramdown
